// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuzUao1k8w-IsscixLYzaeiOvi5K21udA',
    appId: '1:501692998409:web:08a64e38559ea1738469d8',
    messagingSenderId: '501692998409',
    projectId: 'testing-apps-30638',
    authDomain: 'testing-apps-30638.firebaseapp.com',
    storageBucket: 'testing-apps-30638.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhFX9muZiHH60oV4GRnqTxcpUiq8MFZpM',
    appId: '1:501692998409:android:f50bb51912317a2f8469d8',
    messagingSenderId: '501692998409',
    projectId: 'testing-apps-30638',
    storageBucket: 'testing-apps-30638.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Zwq2EnJks0ZmLRpwTgiGANUf2LK4kaU',
    appId: '1:501692998409:ios:a14f125df9d0d7c18469d8',
    messagingSenderId: '501692998409',
    projectId: 'testing-apps-30638',
    storageBucket: 'testing-apps-30638.firebasestorage.app',
    iosBundleId: 'com.example.randomWidgetLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuzUao1k8w-IsscixLYzaeiOvi5K21udA',
    appId: '1:501692998409:web:951596d7248653858469d8',
    messagingSenderId: '501692998409',
    projectId: 'testing-apps-30638',
    authDomain: 'testing-apps-30638.firebaseapp.com',
    storageBucket: 'testing-apps-30638.firebasestorage.app',
  );

}