// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZzYLvj0FAfVQMYnqkUTPY0wm5rc3Ax3c',
    appId: '1:1000312856123:web:b472060ab68399a3b5461e',
    messagingSenderId: '1000312856123',
    projectId: 'auth-384c5',
    authDomain: 'auth-384c5.firebaseapp.com',
    storageBucket: 'auth-384c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWWQEsKbTpydc7ICKlKlU0-iVlYlT6hJw',
    appId: '1:1000312856123:android:2112ed197ba4cdb9b5461e',
    messagingSenderId: '1000312856123',
    projectId: 'auth-384c5',
    storageBucket: 'auth-384c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy8FASXFOyiaEh_c8IpnFlipH6c-90wqE',
    appId: '1:1000312856123:ios:b5d4467ad87d7d2cb5461e',
    messagingSenderId: '1000312856123',
    projectId: 'auth-384c5',
    storageBucket: 'auth-384c5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProjectLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy8FASXFOyiaEh_c8IpnFlipH6c-90wqE',
    appId: '1:1000312856123:ios:b5d4467ad87d7d2cb5461e',
    messagingSenderId: '1000312856123',
    projectId: 'auth-384c5',
    storageBucket: 'auth-384c5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProjectLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZzYLvj0FAfVQMYnqkUTPY0wm5rc3Ax3c',
    appId: '1:1000312856123:web:59ba22ad2d7b8fceb5461e',
    messagingSenderId: '1000312856123',
    projectId: 'auth-384c5',
    authDomain: 'auth-384c5.firebaseapp.com',
    storageBucket: 'auth-384c5.firebasestorage.app',
  );
}
